# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/SWQ2003/Desktop/RISCV_CPU/pipeline_advance/RISCV_CPU.srcs/sources_1/ip/mem/mem.xci
# IP: The module: 'mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SWQ2003/Desktop/RISCV_CPU/pipeline_advance/RISCV_CPU.gen/sources_1/ip/mem/mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/SWQ2003/Desktop/RISCV_CPU/pipeline_advance/RISCV_CPU.srcs/sources_1/ip/mem/mem.xci
# IP: The module: 'mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SWQ2003/Desktop/RISCV_CPU/pipeline_advance/RISCV_CPU.gen/sources_1/ip/mem/mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
