#----------------------------------------------------------------------------------
#-- Engineer: switch_swq
#-- Create Date: 2024/04/18 13:02:24
#----------------------------------------------------------------------------------
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets reset_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets rst_soc_IBUF]
#CLK_100M
set_property PACKAGE_PIN E10 [get_ports clk_in]
set_property IOSTANDARD LVCMOS18 [get_ports clk_in]

#SW0~7
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[0]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[1]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[2]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[3]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[4]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[5]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[6]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[7]}]
set_property PACKAGE_PIN C9         [get_ports {key_in[0]}]
set_property PACKAGE_PIN B9         [get_ports {key_in[1]}]
set_property PACKAGE_PIN G11        [get_ports {key_in[2]}]
set_property PACKAGE_PIN F10        [get_ports {key_in[3]}]
set_property PACKAGE_PIN D10        [get_ports {key_in[4]}]
set_property PACKAGE_PIN E11        [get_ports {key_in[5]}]
set_property PACKAGE_PIN D11        [get_ports {key_in[6]}]
set_property PACKAGE_PIN A14        [get_ports {key_in[7]}]

#SW8~16
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[8]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[9]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[10]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[11]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[12]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[13]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[14]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[15]}]
set_property PACKAGE_PIN B10        [get_ports {key_in[8]}]
set_property PACKAGE_PIN A10        [get_ports {key_in[9]}]
set_property PACKAGE_PIN B15        [get_ports {key_in[10]}]
set_property PACKAGE_PIN A15        [get_ports {key_in[11]}]
set_property PACKAGE_PIN A13        [get_ports {key_in[12]}]
set_property PACKAGE_PIN A12        [get_ports {key_in[13]}]
set_property PACKAGE_PIN D8         [get_ports {key_in[14]}]
set_property PACKAGE_PIN D9         [get_ports {key_in[15]}]

#SW16~23
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[16]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[17]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[18]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[19]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[20]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[21]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[22]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[23]}]
set_property PACKAGE_PIN F8         [get_ports {key_in[16]}]
set_property PACKAGE_PIN F9         [get_ports {key_in[17]}]
set_property PACKAGE_PIN H11        [get_ports {key_in[18]}]
set_property PACKAGE_PIN H12        [get_ports {key_in[19]}]
set_property PACKAGE_PIN G14        [get_ports {key_in[20]}]
set_property PACKAGE_PIN J10        [get_ports {key_in[21]}]
set_property PACKAGE_PIN H14        [get_ports {key_in[22]}]
set_property PACKAGE_PIN J11        [get_ports {key_in[23]}]

#sw31~24
set_property PACKAGE_PIN H13        [get_ports {key_in[24]}]
set_property PACKAGE_PIN J13        [get_ports {key_in[25]}]
set_property PACKAGE_PIN G9         [get_ports {key_in[26]}]
set_property PACKAGE_PIN G10        [get_ports {key_in[27]}]
set_property PACKAGE_PIN H8         [get_ports {key_in[28]}]
set_property PACKAGE_PIN H9         [get_ports {key_in[29]}]
set_property PACKAGE_PIN J14        [get_ports {key_in[30]}]
#set_property PACKAGE_PIN AF12         [get_ports {key_in[31]}]
set_property PACKAGE_PIN J8         [get_ports {key_in[31]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[24]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[25]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[26]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[27]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[28]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[29]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[30]}]
set_property IOSTANDARD LVCMOS18    [get_ports {key_in[31]}]

#SEG_DIG1~16
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[15]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[14]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[13]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[12]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[11]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[10]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[9]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[8]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[7]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[6]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[5]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[4]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[3]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[2]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[1]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[0]}]
set_property PACKAGE_PIN A23        [get_ports {seg_dig[15]}]
set_property PACKAGE_PIN A24        [get_ports {seg_dig[14]}]
set_property PACKAGE_PIN D26        [get_ports {seg_dig[13]}]
set_property PACKAGE_PIN C26        [get_ports {seg_dig[12]}]
set_property PACKAGE_PIN A20        [get_ports {seg_dig[11]}]
set_property PACKAGE_PIN J25        [get_ports {seg_dig[10]}]
set_property PACKAGE_PIN J24        [get_ports {seg_dig[9]}]
set_property PACKAGE_PIN H22        [get_ports {seg_dig[8]}]
set_property PACKAGE_PIN K21        [get_ports {seg_dig[7]}]
set_property PACKAGE_PIN L23        [get_ports {seg_dig[6]}]
set_property PACKAGE_PIN B25        [get_ports {seg_dig[5]}]
set_property PACKAGE_PIN B26        [get_ports {seg_dig[4]}]
set_property PACKAGE_PIN C24        [get_ports {seg_dig[3]}]
set_property PACKAGE_PIN D21        [get_ports {seg_dig[2]}]
set_property PACKAGE_PIN C22        [get_ports {seg_dig[1]}]
set_property PACKAGE_PIN B20        [get_ports {seg_dig[0]}]

#seg_data
set_property PACKAGE_PIN E26        [get_ports {seg_data[7]}]
set_property PACKAGE_PIN J26        [get_ports {seg_data[6]}]
set_property PACKAGE_PIN H26        [get_ports {seg_data[5]}]
set_property PACKAGE_PIN H21        [get_ports {seg_data[4]}]
set_property PACKAGE_PIN G21        [get_ports {seg_data[3]}]
set_property PACKAGE_PIN H23        [get_ports {seg_data[2]}]
set_property PACKAGE_PIN H24        [get_ports {seg_data[1]}]
set_property PACKAGE_PIN J21        [get_ports {seg_data[0]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_data[7]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_data[6]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_data[5]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_data[4]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_data[3]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_data[2]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_data[1]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_data[0]}]

##LED
#set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[0]}]
#set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[1]}]
#set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[2]}]
#set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[3]}]
#set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[4]}]
#set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[5]}]
#set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[6]}]
#set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[7]}]
#set_property PACKAGE_PIN G16			[get_ports {data_out[0]}]
#set_property PACKAGE_PIN H16 			[get_ports {data_out[1]}]
#set_property PACKAGE_PIN D16 			[get_ports {data_out[2]}]
#set_property PACKAGE_PIN D15 			[get_ports {data_out[3]}]
#set_property PACKAGE_PIN C18 			[get_ports {data_out[4]}]
#set_property PACKAGE_PIN C17 			[get_ports {data_out[5]}]
#set_property PACKAGE_PIN B19 			[get_ports {data_out[6]}]
#set_property PACKAGE_PIN C19 			[get_ports {data_out[7]}]

#led0~31
set_property PACKAGE_PIN G16        [get_ports {led[0]}]
set_property PACKAGE_PIN H16        [get_ports {led[1]}]
set_property PACKAGE_PIN D16        [get_ports {led[2]}]
set_property PACKAGE_PIN D15        [get_ports {led[3]}]
set_property PACKAGE_PIN C18        [get_ports {led[4]}]
set_property PACKAGE_PIN C17        [get_ports {led[5]}]
set_property PACKAGE_PIN B19        [get_ports {led[6]}]
set_property PACKAGE_PIN C19        [get_ports {led[7]}]
set_property PACKAGE_PIN A17        [get_ports {led[8]}]
set_property PACKAGE_PIN B17        [get_ports {led[9]}]
set_property PACKAGE_PIN K20        [get_ports {led[10]}]
set_property PACKAGE_PIN J20        [get_ports {led[11]}]
set_property PACKAGE_PIN J18        [get_ports {led[12]}]
set_property PACKAGE_PIN J19        [get_ports {led[13]}]
set_property PACKAGE_PIN L19        [get_ports {led[14]}]
set_property PACKAGE_PIN L20        [get_ports {led[15]}]
set_property PACKAGE_PIN K16        [get_ports {led[16]}]
set_property PACKAGE_PIN K17        [get_ports {led[17]}]
set_property PACKAGE_PIN M17        [get_ports {led[18]}]
set_property PACKAGE_PIN L18        [get_ports {led[19]}]
set_property PACKAGE_PIN L17        [get_ports {led[20]}]
set_property PACKAGE_PIN K18        [get_ports {led[21]}]
set_property PACKAGE_PIN A19        [get_ports {led[22]}]
set_property PACKAGE_PIN A18        [get_ports {led[23]}]
set_property PACKAGE_PIN J16        [get_ports {led[24]}]
set_property PACKAGE_PIN J15        [get_ports {led[25]}]
set_property PACKAGE_PIN B16        [get_ports {led[26]}]
set_property PACKAGE_PIN C16        [get_ports {led[27]}]
set_property PACKAGE_PIN F15        [get_ports {led[28]}]
set_property PACKAGE_PIN M16        [get_ports {led[29]}]
set_property PACKAGE_PIN G15        [get_ports {led[30]}]
set_property PACKAGE_PIN K15        [get_ports {led[31]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[10]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[11]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[12]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[13]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[14]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[15]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[16]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[17]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[18]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[19]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[20]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[21]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[22]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[23]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[24]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[25]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[26]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[27]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[28]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[29]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[30]}]
set_property IOSTANDARD LVCMOS33    [get_ports {led[31]}]

#bin0
set_property IOSTANDARD LVCMOS18 [get_ports reset]
set_property PACKAGE_PIN AC13 [get_ports reset]
#bin1
set_property IOSTANDARD LVCMOS18 [get_ports rst_soc]
#set_property PACKAGE_PIN J8       [get_ports reset]
set_property PACKAGE_PIN AF12 [get_ports rst_soc]

#beep
set_property IOSTANDARD LVCMOS33 [get_ports io_exit]
set_property PACKAGE_PIN F25 [get_ports io_exit]


create_clock -period 10.000 -name clk_in -waveform {0.000 5.000} [get_ports clk_in]
