# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/SWQ2003/Desktop/RISCV_CPU/RISCV_CPU.srcs/sources_1/ip/clk_pll/clk_pll.xci
# IP: The module: 'clk_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SWQ2003/Desktop/RISCV_CPU/RISCV_CPU.gen/sources_1/ip/clk_pll/clk_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/SWQ2003/Desktop/RISCV_CPU/RISCV_CPU.gen/sources_1/ip/clk_pll/clk_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/SWQ2003/Desktop/RISCV_CPU/RISCV_CPU.gen/sources_1/ip/clk_pll/clk_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/SWQ2003/Desktop/RISCV_CPU/RISCV_CPU.srcs/sources_1/ip/clk_pll/clk_pll.xci
# IP: The module: 'clk_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SWQ2003/Desktop/RISCV_CPU/RISCV_CPU.gen/sources_1/ip/clk_pll/clk_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/SWQ2003/Desktop/RISCV_CPU/RISCV_CPU.gen/sources_1/ip/clk_pll/clk_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/SWQ2003/Desktop/RISCV_CPU/RISCV_CPU.gen/sources_1/ip/clk_pll/clk_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
